// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: tunnel-service.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TunnelServiceClient is the client API for TunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TunnelServiceClient interface {
	OpenStream(ctx context.Context, opts ...grpc.CallOption) (TunnelService_OpenStreamClient, error)
}

type tunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelServiceClient(cc grpc.ClientConnInterface) TunnelServiceClient {
	return &tunnelServiceClient{cc}
}

func (c *tunnelServiceClient) OpenStream(ctx context.Context, opts ...grpc.CallOption) (TunnelService_OpenStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &TunnelService_ServiceDesc.Streams[0], "/tunnel_service.TunnelService/OpenStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &tunnelServiceOpenStreamClient{stream}
	return x, nil
}

type TunnelService_OpenStreamClient interface {
	Send(*TunnelServiceRequest) error
	Recv() (*TunnelServiceResponse, error)
	grpc.ClientStream
}

type tunnelServiceOpenStreamClient struct {
	grpc.ClientStream
}

func (x *tunnelServiceOpenStreamClient) Send(m *TunnelServiceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tunnelServiceOpenStreamClient) Recv() (*TunnelServiceResponse, error) {
	m := new(TunnelServiceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TunnelServiceServer is the server API for TunnelService service.
// All implementations must embed UnimplementedTunnelServiceServer
// for forward compatibility
type TunnelServiceServer interface {
	OpenStream(TunnelService_OpenStreamServer) error
	mustEmbedUnimplementedTunnelServiceServer()
}

// UnimplementedTunnelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTunnelServiceServer struct {
}

func (UnimplementedTunnelServiceServer) OpenStream(TunnelService_OpenStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method OpenStream not implemented")
}
func (UnimplementedTunnelServiceServer) mustEmbedUnimplementedTunnelServiceServer() {}

// UnsafeTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServiceServer will
// result in compilation errors.
type UnsafeTunnelServiceServer interface {
	mustEmbedUnimplementedTunnelServiceServer()
}

func RegisterTunnelServiceServer(s grpc.ServiceRegistrar, srv TunnelServiceServer) {
	s.RegisterService(&TunnelService_ServiceDesc, srv)
}

func _TunnelService_OpenStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServiceServer).OpenStream(&tunnelServiceOpenStreamServer{stream})
}

type TunnelService_OpenStreamServer interface {
	Send(*TunnelServiceResponse) error
	Recv() (*TunnelServiceRequest, error)
	grpc.ServerStream
}

type tunnelServiceOpenStreamServer struct {
	grpc.ServerStream
}

func (x *tunnelServiceOpenStreamServer) Send(m *TunnelServiceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tunnelServiceOpenStreamServer) Recv() (*TunnelServiceRequest, error) {
	m := new(TunnelServiceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TunnelService_ServiceDesc is the grpc.ServiceDesc for TunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel_service.TunnelService",
	HandlerType: (*TunnelServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenStream",
			Handler:       _TunnelService_OpenStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tunnel-service.proto",
}
