// Code generated by MockGen. DO NOT EDIT.
// Source: cs3219-project-ay2223s1-g33/session-service/blacklist (interfaces: RedisBlacklistClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	blacklist "cs3219-project-ay2223s1-g33/session-service/blacklist"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRedisBlacklistClient is a mock of RedisBlacklistClient interface.
type MockRedisBlacklistClient struct {
	ctrl     *gomock.Controller
	recorder *MockRedisBlacklistClientMockRecorder
}

// MockRedisBlacklistClientMockRecorder is the mock recorder for MockRedisBlacklistClient.
type MockRedisBlacklistClientMockRecorder struct {
	mock *MockRedisBlacklistClient
}

// NewMockRedisBlacklistClient creates a new mock instance.
func NewMockRedisBlacklistClient(ctrl *gomock.Controller) *MockRedisBlacklistClient {
	mock := &MockRedisBlacklistClient{ctrl: ctrl}
	mock.recorder = &MockRedisBlacklistClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisBlacklistClient) EXPECT() *MockRedisBlacklistClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRedisBlacklistClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockRedisBlacklistClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedisBlacklistClient)(nil).Close))
}

// Connect mocks base method.
func (m *MockRedisBlacklistClient) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockRedisBlacklistClientMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockRedisBlacklistClient)(nil).Connect))
}

// GetChronoBlacklist mocks base method.
func (m *MockRedisBlacklistClient) GetChronoBlacklist() blacklist.TokenBlacklistWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChronoBlacklist")
	ret0, _ := ret[0].(blacklist.TokenBlacklistWriter)
	return ret0
}

// GetChronoBlacklist indicates an expected call of GetChronoBlacklist.
func (mr *MockRedisBlacklistClientMockRecorder) GetChronoBlacklist() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChronoBlacklist", reflect.TypeOf((*MockRedisBlacklistClient)(nil).GetChronoBlacklist))
}

// GetRefreshBlacklist mocks base method.
func (m *MockRedisBlacklistClient) GetRefreshBlacklist() blacklist.TokenBlacklistWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshBlacklist")
	ret0, _ := ret[0].(blacklist.TokenBlacklistWriter)
	return ret0
}

// GetRefreshBlacklist indicates an expected call of GetRefreshBlacklist.
func (mr *MockRedisBlacklistClientMockRecorder) GetRefreshBlacklist() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshBlacklist", reflect.TypeOf((*MockRedisBlacklistClient)(nil).GetRefreshBlacklist))
}

// GetRefreshBlacklistQuerier mocks base method.
func (m *MockRedisBlacklistClient) GetRefreshBlacklistQuerier() blacklist.TokenBlacklistQuerier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshBlacklistQuerier")
	ret0, _ := ret[0].(blacklist.TokenBlacklistQuerier)
	return ret0
}

// GetRefreshBlacklistQuerier indicates an expected call of GetRefreshBlacklistQuerier.
func (mr *MockRedisBlacklistClientMockRecorder) GetRefreshBlacklistQuerier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshBlacklistQuerier", reflect.TypeOf((*MockRedisBlacklistClient)(nil).GetRefreshBlacklistQuerier))
}

// GetSessionBlacklist mocks base method.
func (m *MockRedisBlacklistClient) GetSessionBlacklist() blacklist.TokenBlacklistWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionBlacklist")
	ret0, _ := ret[0].(blacklist.TokenBlacklistWriter)
	return ret0
}

// GetSessionBlacklist indicates an expected call of GetSessionBlacklist.
func (mr *MockRedisBlacklistClientMockRecorder) GetSessionBlacklist() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionBlacklist", reflect.TypeOf((*MockRedisBlacklistClient)(nil).GetSessionBlacklist))
}

// GetSessionBlacklistQuerier mocks base method.
func (m *MockRedisBlacklistClient) GetSessionBlacklistQuerier() blacklist.TokenBlacklistQuerier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionBlacklistQuerier")
	ret0, _ := ret[0].(blacklist.TokenBlacklistQuerier)
	return ret0
}

// GetSessionBlacklistQuerier indicates an expected call of GetSessionBlacklistQuerier.
func (mr *MockRedisBlacklistClientMockRecorder) GetSessionBlacklistQuerier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionBlacklistQuerier", reflect.TypeOf((*MockRedisBlacklistClient)(nil).GetSessionBlacklistQuerier))
}
