name: ci-tests
on: [push, pull_request]

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@main

      - name: Set up repository
        uses: actions/checkout@main
        with:
          ref: main

      - name: Merge to main branch
        run: git checkout --progress --force ${{ github.sha }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Setup CI script'
        run: chmod 755 ./scripts/run-ci.sh

      - name: 'Setup CI script'
        run: chmod 755 ./scripts/run-ci-setup.sh

      - name: 'Setup sub-module NPM'
        run: ./scripts/run-ci-setup.sh

      - name: Run repository-wide tests
        run: ./scripts/run-ci.sh
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@main
      
      - name: Merge to main branch
        run: git checkout --progress --force ${{ github.sha }}

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: 'Add dummy env files'
        run: 'touch matchmaker/.env && touch gateway/.env'

      - name: 'Run matchmaker test'
        run: 'cd matchmaker && make test'

      - name: 'Build Matchmaker'
        run: 'cd matchmaker && make build'

      - name: 'Build Gateway'
        run: 'cd gateway && make build'
